name: build image test 2025-02-28 10:55:49
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key1": "Checkout done"}'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key2": "Login to Docker Hub done"}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key3": "Set up QEMUb done"}'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key4": "Set up Docker Buildx done"}' 
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workspace }}/img.dockerfile
          push: true
          tags: junlong1/puncture:latest
      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key5": "Build and push done"}' 
      - 
        name: 🔎 Check IP
        run: curl https://api.ipify.org

      # - 
      #   name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'http://54.158.74.152:5050'
      #     method: 'POST'
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"key6": "the progress of image build is done"}'