name: my test
on:
	push:
jobs:
  buildpush_ascendai/cann:openeuler-python3.10-cann8.0.0:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ github.workspace }}/img.dockerfile
        push: true
        tags: ascendai/cann:openeuler-python3.10-cann8.0.0
  buildpush_ascendai/cann:openeuler-python3.10-cann8.0.0.beta1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ github.workspace }}/img.dockerfile
        push: true
        tags: ascendai/cann:openeuler-python3.10-cann8.0.0.beta1
